server.port: 8081

spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

#management.security.enabled=false
#management.endpoints.web.exposure.include=*

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672uuuuu
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#eureka.client.region = default
#spring.cloud.config.discovery.service-id=config
#spring.cloud.config.discovery.enabled=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.serviceUrl.defaultZone=https://floating-eyrie-61261.herokuapp.com//eureka/
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://floating-eyrie-61261.herokuapp.com/eureka/
#      defaultZone: http://localhost:8761//eureka/

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-83-201-84.compute-1.amazonaws.com:5432/dev9d14c7kiip4?sslmode=require&user=gqjbwvgtbcfthh&password=91fe711ea8e1eefbeaaf6dcee1d1ca7175eb1bf7887f547bcaa386b07a367a2f
    username: gqjbwvgtbcfthh
    password: 91fe711ea8e1eefbeaaf6dcee1d1ca7175eb1bf7887f547bcaa386b07a367a2f
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect






#spring:
#  cloud:
#    zookeeper:
#      connectString: localhost:2181
#    stream:
#      bindings:
#        pvout:
#          destination: orgChangeTopic
#          producer.header-mode: raw
#          content-type: application/json
#      kafka:
#        binder:
#          configuration:
#            commit.interval.mms: 1000
#            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

#            zkNodes: localhost
#            brokers: localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8000/eureka/