eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://floating-eyrie-61261.herokuapp.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8082